class scoreboard;
        event DONE;
        mailbox #(count_trans) rdmon2sb;
        mailbox #(count_trans) rm2sb;
        count_trans rddata;
        count_trans rmdata;
        count_trans cov_data;
        static int data_verified=0;
        static int rm_count=0;
        static int rd_count=0;


        covergroup cg;
                option.per_instance = 1;
                LOAD  : coverpoint cov_data.load;
                DATA  : coverpoint cov_data.data_in {
                        bins a = {[0:12]};
                        }
                RESET : coverpoint cov_data.resetn;
                MODE  : coverpoint cov_data.mode;
                COUNT : coverpoint cov_data.count{
                        bins c = {[0:12]};
                        }

                cross  LOAD,MODE,DATA;
        endgroup

        function new(mailbox #(count_trans) rdmon2sb,
        mailbox #(count_trans) rm2sb);
                this.rm2sb=rm2sb;
                this.rdmon2sb=rdmon2sb;
                cg = new();
        endfunction

        virtual task start();
        fork
                forever begin
                        rm2sb.get(rmdata);
                        rm_count++;
                        rdmon2sb.get(rddata);
                        rd_count++;
                        check(rddata,rmdata);
                end
        join_none
        endtask

        virtual task check(count_trans rddata,
                   count_trans rmdata);

                if(rmdata.count == rddata.count)
                begin
                        rddata.display("Data from Read Monitor");
                        rmdata.display("Data from Reference Model");
                        $display("No Mismatch");
                end

                else begin
                        rddata.display("Data from Read Monitor");
                        rmdata.display("Data from Reference Model");
                        $display("Mismatch in data");
                end
                data_verified++;
                cov_data = new rmdata;
                cg.sample();

                if(data_verified >= number_of_transactions + 2)
                -> DONE;
        endtask



        virtual task report();
                $display("####Scoreboard Report####");
                $display("Data generated by Read Monitor = %0d", rd_count);
                $display("Data generated by Reference Model = %0d", rm_count);
                $display("Data verified = %0d", data_verified);
        endtask: report

endclass
